name: e2e Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      mariadb:
        image: mariadb
        env:
          MARIADB_ROOT_PASSWORD: sola
        ports:
          - 3306:3306
      searcher:
        image: ghcr.io/leslie-wong-h/trace.moe-worker-searcher:latest
        ports:
          - 19531:19531
        env:
          TRACE_ALGO: cl
          SOLA_SOLR_LIST: http://127.0.0.1:8983/solr/
          SEARCHER_URL: http://127.0.0.1:19531
          MILVUS_URL: 172.17.0.1:19530
      etcd:
        image: quay.io/coreos/etcd:v3.5.0
        env:
          ETCD_AUTO_COMPACTION_MODE: revision
          ETCD_AUTO_COMPACTION_RETENTION: 1000
          ETCD_QUOTA_BACKEND_BYTES: 4294967296
        volumes:
          - ${GITHUB_WORKSPACE}/volumes/etcd:/etcd
      minio:
        image: minio/minio:RELEASE.2022-03-17T06-34-49Z
        env:
          MINIO_ACCESS_KEY: minioadmin
          MINIO_SECRET_KEY: minioadmin
        volumes:
          -  ${GITHUB_WORKSPACE}/volumes/minio:/minio_data
      standalone:
        image: milvusdb/milvus:v2.1.1
        env:
          ETCD_ENDPOINTS: etcd:2379
          MINIO_ADDRESS: minio:9000
        volumes:
          -  ${GITHUB_WORKSPACE}/volumes/milvus:/var/lib/milvus
        ports:
          - 19530:19530
          - 9091:9091

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: run liresolr
        run: |
          sudo mkdir /tmp/solr
          sudo chown 8983:8983 /tmp/solr
          docker run -d -p 8983:8983 -v /tmp/solr:/var/solr soruly/liresolr:latest solr-precreate cl_0 /opt/solr/server/solr/configsets/liresolr
      - name: Install ffmpeg
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ffmpeg --fix-missing
      - name: Initialize etcd 
        run: |
          etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
      - name: Initialize minio
        run: |
          minio server /minio_data
      - name: Initialize milvus-standalone
        run: |
          milvus run standalone
      - run: npm ci
      - run: npm run jest
        env:
          REDIS_HOST: 127.0.0.1
          REDIS_PORT: 6379
          SOLA_DB_HOST: 127.0.0.1
          SOLA_DB_PORT: 3306
          SOLA_DB_USER: root
          SOLA_DB_PWD: sola
          SOLA_DB_NAME: test
          TRACE_ALGO: cl
          SOLA_SOLR_LIST: http://127.0.0.1:8983/solr/
          SOLA_SOLR_SIZE: 1
          TRACE_MEDIA_URL: http://127.0.0.1
          TRACE_MEDIA_SALT: TRACE_MEDIA_SALT
          SEARCHER_URL: http://127.0.0.1:19531
          MILVUS_URL: 172.17.0.1:19530
          TRACE_ACCURACY: 0.02
          TRACE_API_SALT: YOUR_TRACE_API_SALT
          TRACE_API_SECRET: TRACE_API_SECRET
          EMAIL_SMTP: smtp.ethereal.email
          EMAIL_SMTP_PORT: 587
          EMAIL_USER: tracy.christiansen@ethereal.email
          EMAIL_PASS: 8KP4VbHJGq4vAetKPb
      - name: Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
