name: e2e Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      mariadb:
        image: mariadb
        env:
          MARIADB_ROOT_PASSWORD: sola
        ports:
          - 3306:3306
      searcher:
        image: ghcr.io/leslie-wong-h/trace.moe-worker-searcher:latest
        ports:
          - 19531:19531
        env:
          TRACE_ALGO: cl
          SOLA_SOLR_LIST: http://127.0.0.1:8983/solr/
          SEARCHER_URL: http://127.0.0.1:19531
          MILVUS_URL: 172.17.0.1:19530

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: run liresolr
        run: |
          sudo mkdir /tmp/solr
          sudo chown 8983:8983 /tmp/solr
          docker run -d -p 8983:8983 -v /tmp/solr:/var/solr soruly/liresolr:latest solr-precreate cl_0 /opt/solr/server/solr/configsets/liresolr
      - name: Install ffmpeg
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ffmpeg --fix-missing
      - name: Docker run etcd
        run: |
          sudo mkdir /tmp/etcd
          docker run -d --name etcd -v /tmp/etcd:/etcd \
          -e ETCD_AUTO_COMPACTION_MODE=revision \
          -e ETCD_AUTO_COMPACTION_RETENTION=1000 \
          -e ETCD_QUOTA_BACKEND_BYTES=4294967296 \
          quay.io/coreos/etcd:v3.5.0 \
          etcd -advertise-client-urls=http://127.0.0.1:2379 \
          -listen-client-urls http://0.0.0.0:2379 \
          --data-dir /etcd
      - name: Docker run minio
        run: |
          sudo mkdir /tmp/minio
          docker run -d --name minio -v /tmp/minio:/minio_data \
          -e MINIO_ACCESS_KEY=minioadmin \
          -e MINIO_SECRET_KEY=minioadmin \
          minio/minio:RELEASE.2022-03-17T06-34-49Z \
          minio server /minio_data
      - name: Docker run milvus-standalone
        run: |
          sudo mkdir /tmp/milvus
          docker run -d --name standalone -v /tmp/milvus:/var/lib/milvus \
          -p 19530:19530 -p 9091:9091 \
          -e ETCD_ENDPOINTS=etcd:2379 \
          -e MINIO_ADDRESS=minio:9000 \
          milvusdb/milvus:v2.1.1 \
          milvus run standalone
      # Sleep for 30 seconds to wait for Milvus Proxy ready
      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash
      - run: npm ci
      - run: npm run jest
        env:
          REDIS_HOST: 127.0.0.1
          REDIS_PORT: 6379
          SOLA_DB_HOST: 127.0.0.1
          SOLA_DB_PORT: 3306
          SOLA_DB_USER: root
          SOLA_DB_PWD: sola
          SOLA_DB_NAME: test
          TRACE_ALGO: cl
          SOLA_SOLR_LIST: http://127.0.0.1:8983/solr/
          SOLA_SOLR_SIZE: 1
          TRACE_MEDIA_URL: http://127.0.0.1
          TRACE_MEDIA_SALT: TRACE_MEDIA_SALT
          SEARCHER_URL: http://127.0.0.1:19531
          MILVUS_URL: 172.17.0.1:19530
          TRACE_ACCURACY: 0.02
          TRACE_API_SALT: YOUR_TRACE_API_SALT
          TRACE_API_SECRET: TRACE_API_SECRET
          EMAIL_SMTP: smtp.ethereal.email
          EMAIL_SMTP_PORT: 587
          EMAIL_USER: tracy.christiansen@ethereal.email
          EMAIL_PASS: 8KP4VbHJGq4vAetKPb
      - name: Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
